1- Import Libraries & Load the Dataset :
In this step, we import the required Python libraries that will be used throughout the project. Then, we load the dataset into a Pandas DataFrame to begin the data exploration and preprocessing process.

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn  as sns
import pandas as pd 
df = pd.read_csv('Pictures/heart.csv')

2- We display the first few rows of the dataset using df.head() to get a quick overview of the data and verify that it has been loaded correctly.

The dataset contains medical information about patients, including demographic details, clinical measurements, and test results. The objective is to predict whether a patient has heart disease based on these features.

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

3 - Check for Missing Values :
In this step, we check the dataset for missing values because machine learning models cannot be trained on incomplete data. If missing values are found, they must be handled through appropriate preprocessing techniques. Fortunately, this dataset contains no missing values, so it is complete and ready for the next preprocessing steps.

In [4]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

4 - In this step, we separate the dataset into numerical and categorical features. This helps us identify the categorical columns that require preprocessing, such as encoding, since machine learning algorithms can only work with numerical data.

In [5]:
num_cols = [col for col in df.columns if df[col].dtypes != 'object']

In [6]:
num_cols

['Age',
 'RestingBP',
 'Cholesterol',
 'FastingBS',
 'MaxHR',
 'Oldpeak',
 'HeartDisease']

In [7]:
cat_cols = [col for col in df.columns if df[col].dtypes == 'object']

In [8]:
cat_cols

['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

5 - Analyze Categorical Features :
In this step, we analyze the categorical features to understand their distribution. Using the describe() function, we can identify the number of unique values in each feature, the most frequent category, and how many times it appears. This provides valuable insights into the dataset before applying encoding techniques.

In [9]:
df[cat_cols].describe()

        Sex ChestPainType RestingECG ExerciseAngina ST_Slope
count   918           918        918            918      918
unique    2             4          3              2        3
top       M           ASY     Normal              N     Flat
freq    725           496        552            547      460

6 -Encoding Categorical Features :
Machine learning models cannot process categorical (text) data directly. Therefore, categorical features must be converted into numerical values before training the model. In this project, we use two different encoding techniques depending on the nature of the feature.

a- Label Encoding :
Label Encoding assigns a unique integer to each category. It is suitable for binary categorical features (features with only two categories), such as Sex (Male/Female) and ExerciseAngina (Yes/No). Since these features have only two possible values, representing them as 0 and 1 is sufficient and does not introduce unnecessary complexity.

b- One-Hot Encoding :
One-Hot Encoding creates a separate binary column for each category. It is recommended for features that contain more than two categories, such as ChestPainType, RestingECG, and ST_Slope. This approach prevents the model from assuming an incorrect ordinal relationship between categories.

In [10]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

7 - We initialize LabelEncoder and OneHotEncoder objects and assign them to shorter variable names (le and ohe) for easier reuse and improved code readability.

note : The handle_unknown='ignore' parameter ensures that the encoder does not raise an error when it encounters unseen categories during prediction. Instead, unknown categories are ignored, making the model more robust when working with new data.

In [11]:
la = LabelEncoder()
ohe = OneHotEncoder(handle_unknown = 'ignore')

In [12]:
df['sex'] = la.fit_transform(df['Sex'])

8- In this step, we display the encoded values of the Sex column to verify that the categorical labels have been successfully converted into numerical values. This allows us to confirm that the encoding process was applied correctly before proceeding with model training.

In [13]:
df['sex'].value_counts()

sex
1    725
0    193
Name: count, dtype: int64

In [14]:
df['ExerciseAngina'] = la.fit_transform(df['ExerciseAngina'])

In [15]:
df['ExerciseAngina'].value_counts()

ExerciseAngina
0    547
1    371
Name: count, dtype: int64

9- Apply One-Hot Encoding :
In this step, we apply One-Hot Encoding to the ChestPainType feature. Since this column contains multiple categorical values, each category is converted into a separate binary column (0 or 1).

We apply One-Hot Encoding to the ChestPainType column, transforming each category into a separate binary feature. The toarray() method converts the sparse matrix returned by the encoder into a regular NumPy array, making it easier to work with in the following steps.

In [16]:
ch_array = ohe.fit_transform(df[['ChestPainType']]).toarray()

10 - We convert the encoded NumPy array into a Pandas DataFrame and assign meaningful column names using get_feature_names_out(). This improves the readability of the encoded data and makes each generated feature easy to identify.

In [17]:
ch_df = pd.DataFrame(ch_array , columns = ohe.get_feature_names_out())

11- Finally, we display the encoded DataFrame to verify that the ChestPainType column has been successfully transformed into multiple binary features, with each category represented by its own column.

In [18]:
ch_df

     ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA
0                  0.0                1.0                0.0               0.0
1                  0.0                0.0                1.0               0.0
2                  0.0                1.0                0.0               0.0
3                  1.0                0.0                0.0               0.0
4                  0.0                0.0                1.0               0.0
..                 ...                ...                ...               ...
913                0.0                0.0                0.0               1.0
914                1.0                0.0                0.0               0.0
915                1.0                0.0                0.0               0.0
916                0.0                1.0                0.0               0.0
917                0.0                0.0                1.0               0.0

[918 rows x 4 columns]

In [19]:
resting = ohe.fit_transform(df[['RestingECG']]).toarray()

In [20]:
rest_df = pd.DataFrame(resting , columns = ohe.get_feature_names_out())

In [21]:
rest_df

     RestingECG_LVH  RestingECG_Normal  RestingECG_ST
0               0.0                1.0            0.0
1               0.0                1.0            0.0
2               0.0                0.0            1.0
3               0.0                1.0            0.0
4               0.0                1.0            0.0
..              ...                ...            ...
913             0.0                1.0            0.0
914             0.0                1.0            0.0
915             0.0                1.0            0.0
916             1.0                0.0            0.0
917             0.0                1.0            0.0

[918 rows x 3 columns]

In [22]:
st = ohe.fit_transform(df[['ST_Slope']]).toarray()

In [23]:
st_df = pd.DataFrame(st , columns = ohe.get_feature_names_out())

In [24]:
st_df

     ST_Slope_Down  ST_Slope_Flat  ST_Slope_Up
0              0.0            0.0          1.0
1              0.0            1.0          0.0
2              0.0            0.0          1.0
3              0.0            1.0          0.0
4              0.0            0.0          1.0
..             ...            ...          ...
913            0.0            1.0          0.0
914            0.0            1.0          0.0
915            0.0            1.0          0.0
916            0.0            1.0          0.0
917            0.0            0.0          1.0

[918 rows x 3 columns]

12 -We concatenate the newly encoded DataFrame with the original dataset, allowing the encoded features to become part of the main dataset .

In [25]:
df = df.join(ch_df)

In [26]:
df = df.join(rest_df)

In [27]:
df = df.join(st_df)

In [28]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,...,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,M,ATA,140,289,0,Normal,172,0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,49,F,NAP,160,180,0,Normal,156,0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,37,M,ATA,130,283,0,ST,98,0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,48,F,ASY,138,214,0,Normal,108,1,1.5,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,54,M,NAP,150,195,0,Normal,122,0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

13- Remove the Original Categorical Column :

After adding the encoded features to the dataset, we remove the original categorical column because its information is now fully represented by the newly created binary columns. Keeping both the original and encoded columns would result in duplicate information and could negatively affect the model's performance.

In [29]:
df.drop(cat_cols , axis = 1 , inplace = True)

In [30]:
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,sex,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,49,160,180,0,156,1.0,1,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,37,130,283,0,98,0.0,0,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,48,138,214,0,108,1.5,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,54,150,195,0,122,0.0,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

14- Verify Data Types :

In this step, we use the `info()` function to verify the data type of each feature in the dataset. This ensures that all categorical features have been successfully converted into numerical values, making the dataset fully compatible with machine learning algorithms before proceeding to the model training stage.

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   RestingBP          918 non-null    int64
 2   Cholesterol        918 non-null    int64
 3   FastingBS          918 non-null    int64
 4   MaxHR              918 non-null    int64
 5   Oldpeak            918 non-null    float64
 6   HeartDisease       918 non-null    int64
 7   sex                918 non-null    int64
 8   ChestPainType_ASY  918 non-null    float64
 9   ChestPainType_ATA  918 non-null    float64
 10  ChestPainType_NAP  918 non-null    float64
 11  ChestPainType_TA   918 non-null    float64
 12  RestingECG_LVH     918 non-null    float64
 13  RestingECG_Normal  918 non-null    float64
 14  RestingECG_ST      918 non-null    float64
 15  ST_Slope_Down      918 non-null    float64
 16  ST_Slope_Flat      918 non-null    float64
 17  ST_Slope_Up        918 non-null    float64
dtypes: float64(11), int64(7)
memory usage: 129.2 KB

15 - Data Splitting :
The dataset was divided into features (X) and target (y), where HeartDisease was used as the target variable.
Then, the data was split into training and testing sets using train_test_split().
shuffle=True was applied to randomly shuffle the data before splitting, reducing the risk of bias from the original data order.
stratify=y was used to preserve the same class distribution of the target variable in both the training and testing sets, which is important for classification tasks.

In [33]:
from sklearn.model_selection import train_test_split
x =df.drop('HeartDisease' , axis = 1)
y =df['HeartDisease']
xtrain , xtest , ytrain , ytest =train_test_split(x , y , shuffle = True , stratify = y)

15 - Model initialization :
In this step, multiple machine learning models were imported and initialized, including Logistic Regression, K-Nearest Neighbors (KNN), and Decision Tree.
These models were selected as strong baseline classifiers for the heart disease prediction task.
In the next stage, all models will be trained and evaluated, then their performance will be compared to identify the best-performing model

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
lr = LogisticRegression()
kn = KNeighborsClassifier()
dt = DecisionTreeClassifier()

16 - Model Training :
The initialized models were trained on the training set (X_train, y_train) so they could learn patterns from the data and make predictions on heart disease cases.
These trained models will then be evaluated and compared in the next step to determine the best performer.

In [35]:
lr.fit(xtrain , ytrain)
kn.fit(xtrain , ytrain)
dt.fit(xtrain , ytrain)

C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

17 - Model Evaluation :
The trained models were evaluated on both the training and testing sets using accuracy scores to compare their performance and identify the strongest classifier.
A large gap between training and testing accuracy indicates overfitting, while low scores on both sets suggest underfitting.
From the initial results, Logistic Regression achieved the best overall performance. In the next step, hyperparameter tuning will be applied to find the best parameter settings and re-evaluate the models.

In [41]:
print(lr.score(xtrain , ytrain))

0.8691860465116279

In [42]:
print(lr.score(xtest , ytest))

0.8434782608695652

note : no severe overfitting, but it may still be underfitting since both training and testing scores are not particularly high.

In [43]:
print(kn.score(xtrain , ytrain))

0.7877906976744186

In [44]:
print(kn.score(xtest , ytest))

0.7260869565217392

note : clear overfitting

In [45]:
print(dt.score(xtrain , ytrain))

1.0

In [46]:
print(dt.score(xtest , ytest))

0.8304347826086956

KNN Hyperparameter Tuning :
GridSearchCV was used to search for the best hyperparameter combination for the KNN model.
Different values of n_neighbors and p were tested, and the best configuration was found to be n_neighbors=7 and p=1.
The KNN model was then re-trained using these optimized parameters to improve its performance before the final comparison.

In [47]:

from sklearn.model_selection import GridSearchCV

knn = KNeighborsClassifier()

param = {'n_neighbors' : [3 , 5 , 7 ,9 , 11] , 'p' : [1 , 2]}

clf = GridSearchCV(knn , param)
clf.fit(xtrain , ytrain)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2]})

In [48]:
clf.best_params_

{'n_neighbors': 7, 'p': 1}

In [49]:
knn = KNeighborsClassifier(n_neighbors= 7 , p= 1)

In [50]:
knn.fit(xtrain , ytrain)

KNeighborsClassifier(n_neighbors=7, p=1)

note : The model's performance improved after hyperparameter tuning.

In [51]:
print(knn.score(xtrain , ytrain))

0.8008720930232558

In [52]:
print(knn.score(xtest , ytest))

0.7739130434782608

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
dt = DecisionTreeClassifier()
param = {'criterion': ['gini', 'entropy'], 'splitter': ['best', 'random'], 'max_depth': [2, 4, 8, 10, 20, 30], 'min_samples_split': [2, 4, 6, 8], 'min_samples_leaf': [1, 2, 3, 4, 5]}
clf =  GridSearchCV(dt , param , cv = 10)
clf.fit(xtrain , ytrain)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 4, 8, 10, 20, 30],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 4, 6, 8],
                         'splitter': ['best', 'random']})

In [54]:
clf.best_params_

{'criterion': 'entropy',
 'max_depth': 4,
 'min_samples_leaf': 4,
 'min_samples_split': 6,
 'splitter': 'random'}

In [55]:
dt = DecisionTreeClassifier( criterion = 'entropy'  , max_depth = 4 , min_samples_leaf = 4 ,min_samples_split = 6 , splitter = 'random' )

In [56]:
dt.fit(xtrain , ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=4,
                       min_samples_split=6, splitter='random')

note : The model's performance improved after hyperparameter tuning

In [57]:
dt.score(xtrain , ytrain)

0.8677325581395349

In [58]:
dt.score(xtest , ytest)

0.8

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
lr =  LogisticRegression()
params = {'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'], 'max_iter': [100, 1000, 10000]}
clf = GridSearchCV(lr , params , cv = 5 )
clf.fit(xtrain , ytrain)

C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'max_iter': [100, 1000, 10000],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

In [60]:
clf.best_params_

{'max_iter': 100, 'solver': 'lbfgs'}

In [61]:
lr = LogisticRegression( max_iter= 100, solver = 'lbfgs')

note : Even after hyperparameter tuning, Logistic Regression remained the best-performing model among all the evaluated classifiers.

In [62]:
lr.fit(xtrain , ytrain)
lr.score(xtrain , ytrain)

C:\Users\saads\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8691860465116279

In [63]:
lr.score(xtest , ytest)

0.8434782608695652

Another Method for Model Evaluation : 
In addition to using accuracy scores, another useful way to evaluate a classification model is through the confusion matrix.
While accuracy provides an overall measure of correct predictions, the confusion matrix offers a more detailed view of the model’s performance by showing how predictions are distributed across the actual and predicted classes.
The confusion matrix is composed of four main outcomes:
True Negatives (TN): cases that were correctly predicted as non-heart disease
False Positives (FP): healthy cases that were incorrectly predicted as heart disease
False Negatives (FN): heart disease cases that were incorrectly predicted as healthy
True Positives (TP): cases that were correctly predicted as heart disease
This makes the confusion matrix especially useful for understanding the types of errors made by the model, rather than relying only on a single performance metric such as accuracy

In [64]:
from sklearn.metrics import confusion_matrix
yhatlr = lr.predict(xtest)

In [65]:
confusion_matrix(ytest , yhatlr)

array([[ 80,  23],
       [ 13, 114]])

In [1]:
accuracy = (80 + 114) / (23 + 80 + 13 + 114)
accuracy

0.8434782608695652